In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
train_data = pd.read_csv('train.csv')

In [3]:
train_data

,ID,District,Block,CultLand,CropCultLand,LandPreparationMethod,CropTillageDate,CropTillageDepth,CropEstMethod,RcNursEstDate,...,Harv_method,Harv_date,Harv_hand_rent,Threshing_date,Threshing_method,Residue_length,Residue_perc,Stubble_use,Acre,Yield
0,ID_GTFAC7PEVWQ9,Nalanda,Noorsarai,45,40,TractorPlough FourWheelTracRotavator,2022-07-20,5,Manual_PuddledRandom,2022-06-27,...,machine,2022-11-16,NaN,2022-11-16,machine,30,40,plowed_in_soil,0.312500,600
1,ID_TK40ARLSPOKS,Nalanda,Rajgir,26,26,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-18,5,Manual_PuddledRandom,2022-06-20,...,hand,2022-11-25,3.0,2022-12-24,machine,24,10,plowed_in_soil,0.312500,600
2,ID_1FJY2CRIMLZZ,Gaya,Gurua,10,10,TractorPlough FourWheelTracRotavator,2022-06-30,6,Manual_PuddledRandom,2022-06-20,...,hand,2022-12-12,480.0,2023-01-11,machine,30,10,plowed_in_soil,0.148148,225
3,ID_I3IPXS4DB7NE,Gaya,Gurua,15,15,TractorPlough FourWheelTracRotavator,2022-06-16,6,Manual_PuddledRandom,2022-06-17,...,hand,2022-12-02,240.0,2022-12-29,hand,26,10,plowed_in_soil,0.222222,468
4,ID_4T8YQWXWHB4A,Nalanda,Noorsarai,60,60,TractorPlough WetTillagePuddling,2022-07-19,4,Manual_PuddledRandom,2022-06-21,...,machine,2022-11-30,NaN,2022-12-02,machine,24,40,plowed_in_soil,0.468750,550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,ID_7ZZQ6R4XB4FK,Nalanda,Rajgir,28,28,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-02,6,LineSowingAfterTillage,2022-06-29,...,machine,2022-11-29,NaN,2022-12-14,machine,25,40,plowed_in_soil,0.375000,720
3866,ID_PVVDF6LK6FO8,Vaishali,Mahua,5,5,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-06,5,Manual_PuddledRandom,2022-07-08,...,hand,2022-10-10,4.0,2022-11-05,hand,30,10,plowed_in_soil,0.136364,250
3867,ID_RBYVUPRATVMW,Nalanda,Noorsarai,50,45,TractorPlough,2022-07-07,5,Manual_PuddledRandom,2022-06-15,...,hand,2022-10-20,1200.0,2022-10-30,hand,25,10,plowed_in_soil,0.375000,600
3868,ID_ARE9QWENJNJ2,Jamui,Khaira,20,20,TractorPlough,2022-07-12,3,Manual_PuddledRandom,2022-06-28,...,hand,2022-11-09,100.0,2022-12-10,hand,25,10,plowed_in_soil,0.227273,400
3869,ID_KEPOQDTCZC6S,Jamui,Jamui,4,4,TractorPlough,2022-07-24,4,Manual_PuddledRandom,2022-06-25,...,hand,2022-11-17,300.0,2022-12-29,machine,27,10,plowed_in_soil,0.136364,238

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3870 entries, 0 to 3869
Data columns (total 44 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  3870 non-null   object
 1   District                            3870 non-null   object
 2   Block                               3870 non-null   object
 3   CultLand                            3870 non-null   int64
 4   CropCultLand                        3870 non-null   int64
 5   LandPreparationMethod               3870 non-null   object
 6   CropTillageDate                     3870 non-null   object
 7   CropTillageDepth                    3870 non-null   int64
 8   CropEstMethod                       3870 non-null   object
 9   RcNursEstDate                       3787 non-null   object
 10  SeedingSowingTransplanting          3870 non-null   object
 11  SeedlingsPerPit                     3581 non-null   float64
 12  NursDetFactor                       3581 non-null   object
 13  TransDetFactor                      3581 non-null   object
 14  TransplantingIrrigationHours        3677 non-null   float64
 15  TransplantingIrrigationSource       3755 non-null   object
 16  TransplantingIrrigationPowerSource  3367 non-null   object
 17  TransIrriCost                       2988 non-null   float64
 18  StandingWater                       3632 non-null   float64
 19  OrgFertilizers                      2535 non-null   object
 20  Ganaura                             1453 non-null   float64
 21  CropOrgFYM                          1196 non-null   float64
 22  PCropSolidOrgFertAppMethod          2533 non-null   object
 23  NoFertilizerAppln                   3870 non-null   int64
 24  CropbasalFerts                      3682 non-null   object
 25  BasalDAP                            3327 non-null   float64
 26  BasalUrea                           2166 non-null   float64
 27  MineralFertAppMethod                3870 non-null   object
 28  FirstTopDressFert                   3385 non-null   object
 29  1tdUrea                             3314 non-null   float64
 30  1appDaysUrea                        3314 non-null   float64
 31  2tdUrea                             1176 non-null   float64
 32  2appDaysUrea                        1170 non-null   float64
 33  MineralFertAppMethod.1              3389 non-null   object
 34  Harv_method                         3870 non-null   object
 35  Harv_date                           3870 non-null   object
 36  Harv_hand_rent                      3618 non-null   float64
 37  Threshing_date                      3870 non-null   object
 38  Threshing_method                    3870 non-null   object
 39  Residue_length                      3870 non-null   int64
 40  Residue_perc                        3870 non-null   int64
 41  Stubble_use                         3870 non-null   object
 42  Acre                                3870 non-null   float64
 43  Yield                               3870 non-null   int64
dtypes: float64(14), int64(7), object(23)
memory usage: 1.3+ MB

In [8]:
columns_missing_values = [column for column in train_data.columns if train_data[column].notnull().sum() < 3000]
columns_missing_values

['TransIrriCost',
 'OrgFertilizers',
 'Ganaura',
 'CropOrgFYM',
 'PCropSolidOrgFertAppMethod',
 'BasalUrea',
 '2tdUrea',
 '2appDaysUrea']

In [10]:
train_data_after_dropping = train_data.copy()
train_data_after_dropping = train_data.drop(columns = columns_missing_values)

In [11]:
train_data_after_dropping

,ID,District,Block,CultLand,CropCultLand,LandPreparationMethod,CropTillageDate,CropTillageDepth,CropEstMethod,RcNursEstDate,...,Harv_method,Harv_date,Harv_hand_rent,Threshing_date,Threshing_method,Residue_length,Residue_perc,Stubble_use,Acre,Yield
0,ID_GTFAC7PEVWQ9,Nalanda,Noorsarai,45,40,TractorPlough FourWheelTracRotavator,2022-07-20,5,Manual_PuddledRandom,2022-06-27,...,machine,2022-11-16,NaN,2022-11-16,machine,30,40,plowed_in_soil,0.312500,600
1,ID_TK40ARLSPOKS,Nalanda,Rajgir,26,26,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-18,5,Manual_PuddledRandom,2022-06-20,...,hand,2022-11-25,3.0,2022-12-24,machine,24,10,plowed_in_soil,0.312500,600
2,ID_1FJY2CRIMLZZ,Gaya,Gurua,10,10,TractorPlough FourWheelTracRotavator,2022-06-30,6,Manual_PuddledRandom,2022-06-20,...,hand,2022-12-12,480.0,2023-01-11,machine,30,10,plowed_in_soil,0.148148,225
3,ID_I3IPXS4DB7NE,Gaya,Gurua,15,15,TractorPlough FourWheelTracRotavator,2022-06-16,6,Manual_PuddledRandom,2022-06-17,...,hand,2022-12-02,240.0,2022-12-29,hand,26,10,plowed_in_soil,0.222222,468
4,ID_4T8YQWXWHB4A,Nalanda,Noorsarai,60,60,TractorPlough WetTillagePuddling,2022-07-19,4,Manual_PuddledRandom,2022-06-21,...,machine,2022-11-30,NaN,2022-12-02,machine,24,40,plowed_in_soil,0.468750,550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,ID_7ZZQ6R4XB4FK,Nalanda,Rajgir,28,28,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-02,6,LineSowingAfterTillage,2022-06-29,...,machine,2022-11-29,NaN,2022-12-14,machine,25,40,plowed_in_soil,0.375000,720
3866,ID_PVVDF6LK6FO8,Vaishali,Mahua,5,5,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-06,5,Manual_PuddledRandom,2022-07-08,...,hand,2022-10-10,4.0,2022-11-05,hand,30,10,plowed_in_soil,0.136364,250
3867,ID_RBYVUPRATVMW,Nalanda,Noorsarai,50,45,TractorPlough,2022-07-07,5,Manual_PuddledRandom,2022-06-15,...,hand,2022-10-20,1200.0,2022-10-30,hand,25,10,plowed_in_soil,0.375000,600
3868,ID_ARE9QWENJNJ2,Jamui,Khaira,20,20,TractorPlough,2022-07-12,3,Manual_PuddledRandom,2022-06-28,...,hand,2022-11-09,100.0,2022-12-10,hand,25,10,plowed_in_soil,0.227273,400
3869,ID_KEPOQDTCZC6S,Jamui,Jamui,4,4,TractorPlough,2022-07-24,4,Manual_PuddledRandom,2022-06-25,...,hand,2022-11-17,300.0,2022-12-29,machine,27,10,plowed_in_soil,0.136364,238

In [12]:
train_data_after_dropping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3870 entries, 0 to 3869
Data columns (total 36 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  3870 non-null   object
 1   District                            3870 non-null   object
 2   Block                               3870 non-null   object
 3   CultLand                            3870 non-null   int64
 4   CropCultLand                        3870 non-null   int64
 5   LandPreparationMethod               3870 non-null   object
 6   CropTillageDate                     3870 non-null   object
 7   CropTillageDepth                    3870 non-null   int64
 8   CropEstMethod                       3870 non-null   object
 9   RcNursEstDate                       3787 non-null   object
 10  SeedingSowingTransplanting          3870 non-null   object
 11  SeedlingsPerPit                     3581 non-null   float64
 12  NursDetFactor                       3581 non-null   object
 13  TransDetFactor                      3581 non-null   object
 14  TransplantingIrrigationHours        3677 non-null   float64
 15  TransplantingIrrigationSource       3755 non-null   object
 16  TransplantingIrrigationPowerSource  3367 non-null   object
 17  StandingWater                       3632 non-null   float64
 18  NoFertilizerAppln                   3870 non-null   int64
 19  CropbasalFerts                      3682 non-null   object
 20  BasalDAP                            3327 non-null   float64
 21  MineralFertAppMethod                3870 non-null   object
 22  FirstTopDressFert                   3385 non-null   object
 23  1tdUrea                             3314 non-null   float64
 24  1appDaysUrea                        3314 non-null   float64
 25  MineralFertAppMethod.1              3389 non-null   object
 26  Harv_method                         3870 non-null   object
 27  Harv_date                           3870 non-null   object
 28  Harv_hand_rent                      3618 non-null   float64
 29  Threshing_date                      3870 non-null   object
 30  Threshing_method                    3870 non-null   object
 31  Residue_length                      3870 non-null   int64
 32  Residue_perc                        3870 non-null   int64
 33  Stubble_use                         3870 non-null   object
 34  Acre                                3870 non-null   float64
 35  Yield                               3870 non-null   int64
dtypes: float64(8), int64(7), object(21)
memory usage: 1.1+ MB

In [14]:
from sklearn.impute import SimpleImputer

In [15]:
train_data_after_dropping

,ID,District,Block,CultLand,CropCultLand,LandPreparationMethod,CropTillageDate,CropTillageDepth,CropEstMethod,RcNursEstDate,...,Harv_method,Harv_date,Harv_hand_rent,Threshing_date,Threshing_method,Residue_length,Residue_perc,Stubble_use,Acre,Yield
0,ID_GTFAC7PEVWQ9,Nalanda,Noorsarai,45,40,TractorPlough FourWheelTracRotavator,2022-07-20,5,Manual_PuddledRandom,2022-06-27,...,machine,2022-11-16,NaN,2022-11-16,machine,30,40,plowed_in_soil,0.312500,600
1,ID_TK40ARLSPOKS,Nalanda,Rajgir,26,26,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-18,5,Manual_PuddledRandom,2022-06-20,...,hand,2022-11-25,3.0,2022-12-24,machine,24,10,plowed_in_soil,0.312500,600
2,ID_1FJY2CRIMLZZ,Gaya,Gurua,10,10,TractorPlough FourWheelTracRotavator,2022-06-30,6,Manual_PuddledRandom,2022-06-20,...,hand,2022-12-12,480.0,2023-01-11,machine,30,10,plowed_in_soil,0.148148,225
3,ID_I3IPXS4DB7NE,Gaya,Gurua,15,15,TractorPlough FourWheelTracRotavator,2022-06-16,6,Manual_PuddledRandom,2022-06-17,...,hand,2022-12-02,240.0,2022-12-29,hand,26,10,plowed_in_soil,0.222222,468
4,ID_4T8YQWXWHB4A,Nalanda,Noorsarai,60,60,TractorPlough WetTillagePuddling,2022-07-19,4,Manual_PuddledRandom,2022-06-21,...,machine,2022-11-30,NaN,2022-12-02,machine,24,40,plowed_in_soil,0.468750,550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,ID_7ZZQ6R4XB4FK,Nalanda,Rajgir,28,28,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-02,6,LineSowingAfterTillage,2022-06-29,...,machine,2022-11-29,NaN,2022-12-14,machine,25,40,plowed_in_soil,0.375000,720
3866,ID_PVVDF6LK6FO8,Vaishali,Mahua,5,5,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-06,5,Manual_PuddledRandom,2022-07-08,...,hand,2022-10-10,4.0,2022-11-05,hand,30,10,plowed_in_soil,0.136364,250
3867,ID_RBYVUPRATVMW,Nalanda,Noorsarai,50,45,TractorPlough,2022-07-07,5,Manual_PuddledRandom,2022-06-15,...,hand,2022-10-20,1200.0,2022-10-30,hand,25,10,plowed_in_soil,0.375000,600
3868,ID_ARE9QWENJNJ2,Jamui,Khaira,20,20,TractorPlough,2022-07-12,3,Manual_PuddledRandom,2022-06-28,...,hand,2022-11-09,100.0,2022-12-10,hand,25,10,plowed_in_soil,0.227273,400
3869,ID_KEPOQDTCZC6S,Jamui,Jamui,4,4,TractorPlough,2022-07-24,4,Manual_PuddledRandom,2022-06-25,...,hand,2022-11-17,300.0,2022-12-29,machine,27,10,plowed_in_soil,0.136364,238

In [24]:
for i in train_data_after_dropping.columns:
    if train_data_after_dropping[i].dtype == 'object':
        print(i, train_data_after_dropping[i].isnull().sum())

ID 0
District 0
Block 0
LandPreparationMethod 0
CropTillageDate 0
CropEstMethod 0
RcNursEstDate 83
SeedingSowingTransplanting 0
NursDetFactor 289
TransDetFactor 289
TransplantingIrrigationSource 115
TransplantingIrrigationPowerSource 503
CropbasalFerts 188
MineralFertAppMethod 0
FirstTopDressFert 485
MineralFertAppMethod.1 481
Harv_method 0
Harv_date 0
Threshing_date 0
Threshing_method 0
Stubble_use 0

In [27]:
train_data_after_dropping['RcNursEstDate'] = pd.to_datetime(train_data_after_dropping['RcNursEstDate'])

In [28]:
columns_missing_greater_than_0 = []
for i in train_data_after_dropping.columns:
    if train_data_after_dropping[i].dtype == 'object':
        if train_data_after_dropping[i].isnull().sum() > 0:
            columns_missing_greater_than_0.append(i)
columns_missing_greater_than_0

['NursDetFactor',
 'TransDetFactor',
 'TransplantingIrrigationSource',
 'TransplantingIrrigationPowerSource',
 'CropbasalFerts',
 'FirstTopDressFert',
 'MineralFertAppMethod.1']

In [34]:
categorical_imputer = SimpleImputer(strategy='most_frequent')
train_data_after_imputation = train_data_after_dropping.copy()

train_data_after_imputation[columns_missing_greater_than_0] = categorical_imputer.fit_transform(
    train_data_after_dropping[columns_missing_greater_than_0]
)

In [35]:
train_data_after_imputation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3870 entries, 0 to 3869
Data columns (total 36 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  3870 non-null   object
 1   District                            3870 non-null   object
 2   Block                               3870 non-null   object
 3   CultLand                            3870 non-null   int64
 4   CropCultLand                        3870 non-null   int64
 5   LandPreparationMethod               3870 non-null   object
 6   CropTillageDate                     3870 non-null   object
 7   CropTillageDepth                    3870 non-null   int64
 8   CropEstMethod                       3870 non-null   object
 9   RcNursEstDate                       3787 non-null   datetime64[ns]
 10  SeedingSowingTransplanting          3870 non-null   object
 11  SeedlingsPerPit                     3581 non-null   float64
 12  NursDetFactor                       3870 non-null   object
 13  TransDetFactor                      3870 non-null   object
 14  TransplantingIrrigationHours        3677 non-null   float64
 15  TransplantingIrrigationSource       3870 non-null   object
 16  TransplantingIrrigationPowerSource  3870 non-null   object
 17  StandingWater                       3632 non-null   float64
 18  NoFertilizerAppln                   3870 non-null   int64
 19  CropbasalFerts                      3870 non-null   object
 20  BasalDAP                            3327 non-null   float64
 21  MineralFertAppMethod                3870 non-null   object
 22  FirstTopDressFert                   3870 non-null   object
 23  1tdUrea                             3314 non-null   float64
 24  1appDaysUrea                        3314 non-null   float64
 25  MineralFertAppMethod.1              3870 non-null   object
 26  Harv_method                         3870 non-null   object
 27  Harv_date                           3870 non-null   object
 28  Harv_hand_rent                      3618 non-null   float64
 29  Threshing_date                      3870 non-null   object
 30  Threshing_method                    3870 non-null   object
 31  Residue_length                      3870 non-null   int64
 32  Residue_perc                        3870 non-null   int64
 33  Stubble_use                         3870 non-null   object
 34  Acre                                3870 non-null   float64
 35  Yield                               3870 non-null   int64
dtypes: datetime64[ns](1), float64(8), int64(7), object(20)
memory usage: 1.1+ MB

In [37]:
train_data_after_imputation = train_data_after_imputation.drop(columns = ['RcNursEstDate'])

In [41]:
for i in train_data_after_imputation.columns:
    if train_data_after_imputation[i].dtype == 'object':
        print(i, train_data_after_imputation[i].nunique())

ID 3870
District 4
Block 9
LandPreparationMethod 43
CropTillageDate 78
CropEstMethod 4
SeedingSowingTransplanting 62
NursDetFactor 125
TransDetFactor 155
TransplantingIrrigationSource 6
TransplantingIrrigationPowerSource 3
CropbasalFerts 34
MineralFertAppMethod 3
FirstTopDressFert 14
MineralFertAppMethod.1 3
Harv_method 2
Harv_date 107
Threshing_date 162
Threshing_method 2
Stubble_use 2

In [42]:
train_data_after_imputation['CropTillageDate'] = pd.to_datetime(train_data_after_imputation['CropTillageDate'])
train_data_after_imputation['Harv_date'] = pd.to_datetime(train_data_after_imputation['Harv_date'])
train_data_after_imputation['Threshing_date'] = pd.to_datetime(train_data_after_imputation['Threshing_date'])

In [43]:
train_data_after_imputation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3870 entries, 0 to 3869
Data columns (total 35 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  3870 non-null   object
 1   District                            3870 non-null   object
 2   Block                               3870 non-null   object
 3   CultLand                            3870 non-null   int64
 4   CropCultLand                        3870 non-null   int64
 5   LandPreparationMethod               3870 non-null   object
 6   CropTillageDate                     3870 non-null   datetime64[ns]
 7   CropTillageDepth                    3870 non-null   int64
 8   CropEstMethod                       3870 non-null   object
 9   SeedingSowingTransplanting          3870 non-null   object
 10  SeedlingsPerPit                     3581 non-null   float64
 11  NursDetFactor                       3870 non-null   object
 12  TransDetFactor                      3870 non-null   object
 13  TransplantingIrrigationHours        3677 non-null   float64
 14  TransplantingIrrigationSource       3870 non-null   object
 15  TransplantingIrrigationPowerSource  3870 non-null   object
 16  StandingWater                       3632 non-null   float64
 17  NoFertilizerAppln                   3870 non-null   int64
 18  CropbasalFerts                      3870 non-null   object
 19  BasalDAP                            3327 non-null   float64
 20  MineralFertAppMethod                3870 non-null   object
 21  FirstTopDressFert                   3870 non-null   object
 22  1tdUrea                             3314 non-null   float64
 23  1appDaysUrea                        3314 non-null   float64
 24  MineralFertAppMethod.1              3870 non-null   object
 25  Harv_method                         3870 non-null   object
 26  Harv_date                           3870 non-null   datetime64[ns]
 27  Harv_hand_rent                      3618 non-null   float64
 28  Threshing_date                      3870 non-null   datetime64[ns]
 29  Threshing_method                    3870 non-null   object
 30  Residue_length                      3870 non-null   int64
 31  Residue_perc                        3870 non-null   int64
 32  Stubble_use                         3870 non-null   object
 33  Acre                                3870 non-null   float64
 34  Yield                               3870 non-null   int64
dtypes: datetime64[ns](3), float64(8), int64(7), object(17)
memory usage: 1.0+ MB

In [46]:
encoder = LabelEncoder()
columns_for_encoding = []
for i in train_data_after_imputation.columns:
    if train_data_after_imputation[i].dtype == 'object' and i != 'ID':
        columns_for_encoding.append(i)
train_data_after_encoding = train_data_after_imputation.copy()
for i in columns_for_encoding:
    train_data_after_encoding[i] = encoder.fit_transform(train_data_after_imputation[i])

In [47]:
train_data_after_encoding

,ID,District,Block,CultLand,CropCultLand,LandPreparationMethod,CropTillageDate,CropTillageDepth,CropEstMethod,SeedingSowingTransplanting,...,Harv_method,Harv_date,Harv_hand_rent,Threshing_date,Threshing_method,Residue_length,Residue_perc,Stubble_use,Acre,Yield
0,ID_GTFAC7PEVWQ9,2,6,45,40,18,2022-07-20,5,3,20,...,1,2022-11-16,NaN,2022-11-16,1,30,40,1,0.312500,600
1,ID_TK40ARLSPOKS,2,7,26,26,41,2022-07-18,5,3,19,...,0,2022-11-25,3.0,2022-12-24,1,24,10,1,0.312500,600
2,ID_1FJY2CRIMLZZ,0,2,10,10,18,2022-06-30,6,3,43,...,0,2022-12-12,480.0,2023-01-11,1,30,10,1,0.148148,225
3,ID_I3IPXS4DB7NE,0,2,15,15,18,2022-06-16,6,3,16,...,0,2022-12-02,240.0,2022-12-29,0,26,10,1,0.222222,468
4,ID_4T8YQWXWHB4A,2,6,60,60,24,2022-07-19,4,3,19,...,1,2022-11-30,NaN,2022-12-02,1,24,40,1,0.468750,550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,ID_7ZZQ6R4XB4FK,2,7,28,28,41,2022-07-02,6,1,15,...,1,2022-11-29,NaN,2022-12-14,1,25,40,1,0.375000,720
3866,ID_PVVDF6LK6FO8,3,5,5,5,41,2022-07-06,5,3,29,...,0,2022-10-10,4.0,2022-11-05,0,30,10,1,0.136364,250
3867,ID_RBYVUPRATVMW,2,6,50,45,15,2022-07-07,5,3,7,...,0,2022-10-20,1200.0,2022-10-30,0,25,10,1,0.375000,600
3868,ID_ARE9QWENJNJ2,1,4,20,20,15,2022-07-12,3,3,23,...,0,2022-11-09,100.0,2022-12-10,0,25,10,1,0.227273,400
3869,ID_KEPOQDTCZC6S,1,3,4,4,15,2022-07-24,4,3,27,...,0,2022-11-17,300.0,2022-12-29,1,27,10,1,0.136364,238

In [48]:
train_data_after_encoding.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3870 entries, 0 to 3869
Data columns (total 35 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  3870 non-null   object
 1   District                            3870 non-null   int64
 2   Block                               3870 non-null   int64
 3   CultLand                            3870 non-null   int64
 4   CropCultLand                        3870 non-null   int64
 5   LandPreparationMethod               3870 non-null   int64
 6   CropTillageDate                     3870 non-null   datetime64[ns]
 7   CropTillageDepth                    3870 non-null   int64
 8   CropEstMethod                       3870 non-null   int64
 9   SeedingSowingTransplanting          3870 non-null   int64
 10  SeedlingsPerPit                     3581 non-null   float64
 11  NursDetFactor                       3870 non-null   int64
 12  TransDetFactor                      3870 non-null   int64
 13  TransplantingIrrigationHours        3677 non-null   float64
 14  TransplantingIrrigationSource       3870 non-null   int64
 15  TransplantingIrrigationPowerSource  3870 non-null   int64
 16  StandingWater                       3632 non-null   float64
 17  NoFertilizerAppln                   3870 non-null   int64
 18  CropbasalFerts                      3870 non-null   int64
 19  BasalDAP                            3327 non-null   float64
 20  MineralFertAppMethod                3870 non-null   int64
 21  FirstTopDressFert                   3870 non-null   int64
 22  1tdUrea                             3314 non-null   float64
 23  1appDaysUrea                        3314 non-null   float64
 24  MineralFertAppMethod.1              3870 non-null   int64
 25  Harv_method                         3870 non-null   int64
 26  Harv_date                           3870 non-null   datetime64[ns]
 27  Harv_hand_rent                      3618 non-null   float64
 28  Threshing_date                      3870 non-null   datetime64[ns]
 29  Threshing_method                    3870 non-null   int64
 30  Residue_length                      3870 non-null   int64
 31  Residue_perc                        3870 non-null   int64
 32  Stubble_use                         3870 non-null   int64
 33  Acre                                3870 non-null   float64
 34  Yield                               3870 non-null   int64
dtypes: datetime64[ns](3), float64(8), int64(23), object(1)
memory usage: 1.0+ MB

In [49]:
cols_for_imputation = []
for i in train_data_after_encoding.columns:
    if train_data_after_encoding[i].isnull().sum() > 0:
        cols_for_imputation.append(i)
cols_for_imputation

['SeedlingsPerPit',
 'TransplantingIrrigationHours',
 'StandingWater',
 'BasalDAP',
 '1tdUrea',
 '1appDaysUrea',
 'Harv_hand_rent']

In [53]:
imputer = SimpleImputer(strategy = 'median')
dataset = train_data_after_encoding.copy()
dataset[cols_for_imputation] = imputer.fit_transform(train_data_after_encoding[cols_for_imputation])

In [54]:
dataset

,ID,District,Block,CultLand,CropCultLand,LandPreparationMethod,CropTillageDate,CropTillageDepth,CropEstMethod,SeedingSowingTransplanting,...,Harv_method,Harv_date,Harv_hand_rent,Threshing_date,Threshing_method,Residue_length,Residue_perc,Stubble_use,Acre,Yield
0,ID_GTFAC7PEVWQ9,2,6,45,40,18,2022-07-20,5,3,20,...,1,2022-11-16,400.0,2022-11-16,1,30,40,1,0.312500,600
1,ID_TK40ARLSPOKS,2,7,26,26,41,2022-07-18,5,3,19,...,0,2022-11-25,3.0,2022-12-24,1,24,10,1,0.312500,600
2,ID_1FJY2CRIMLZZ,0,2,10,10,18,2022-06-30,6,3,43,...,0,2022-12-12,480.0,2023-01-11,1,30,10,1,0.148148,225
3,ID_I3IPXS4DB7NE,0,2,15,15,18,2022-06-16,6,3,16,...,0,2022-12-02,240.0,2022-12-29,0,26,10,1,0.222222,468
4,ID_4T8YQWXWHB4A,2,6,60,60,24,2022-07-19,4,3,19,...,1,2022-11-30,400.0,2022-12-02,1,24,40,1,0.468750,550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3865,ID_7ZZQ6R4XB4FK,2,7,28,28,41,2022-07-02,6,1,15,...,1,2022-11-29,400.0,2022-12-14,1,25,40,1,0.375000,720
3866,ID_PVVDF6LK6FO8,3,5,5,5,41,2022-07-06,5,3,29,...,0,2022-10-10,4.0,2022-11-05,0,30,10,1,0.136364,250
3867,ID_RBYVUPRATVMW,2,6,50,45,15,2022-07-07,5,3,7,...,0,2022-10-20,1200.0,2022-10-30,0,25,10,1,0.375000,600
3868,ID_ARE9QWENJNJ2,1,4,20,20,15,2022-07-12,3,3,23,...,0,2022-11-09,100.0,2022-12-10,0,25,10,1,0.227273,400
3869,ID_KEPOQDTCZC6S,1,3,4,4,15,2022-07-24,4,3,27,...,0,2022-11-17,300.0,2022-12-29,1,27,10,1,0.136364,238

In [59]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3870 entries, 0 to 3869
Data columns (total 35 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  3870 non-null   object
 1   District                            3870 non-null   int64
 2   Block                               3870 non-null   int64
 3   CultLand                            3870 non-null   int64
 4   CropCultLand                        3870 non-null   int64
 5   LandPreparationMethod               3870 non-null   int64
 6   CropTillageDate                     3870 non-null   datetime64[ns]
 7   CropTillageDepth                    3870 non-null   int64
 8   CropEstMethod                       3870 non-null   int64
 9   SeedingSowingTransplanting          3870 non-null   int64
 10  SeedlingsPerPit                     3870 non-null   float64
 11  NursDetFactor                       3870 non-null   int64
 12  TransDetFactor                      3870 non-null   int64
 13  TransplantingIrrigationHours        3870 non-null   float64
 14  TransplantingIrrigationSource       3870 non-null   int64
 15  TransplantingIrrigationPowerSource  3870 non-null   int64
 16  StandingWater                       3870 non-null   float64
 17  NoFertilizerAppln                   3870 non-null   int64
 18  CropbasalFerts                      3870 non-null   int64
 19  BasalDAP                            3870 non-null   float64
 20  MineralFertAppMethod                3870 non-null   int64
 21  FirstTopDressFert                   3870 non-null   int64
 22  1tdUrea                             3870 non-null   float64
 23  1appDaysUrea                        3870 non-null   float64
 24  MineralFertAppMethod.1              3870 non-null   int64
 25  Harv_method                         3870 non-null   int64
 26  Harv_date                           3870 non-null   datetime64[ns]
 27  Harv_hand_rent                      3870 non-null   float64
 28  Threshing_date                      3870 non-null   datetime64[ns]
 29  Threshing_method                    3870 non-null   int64
 30  Residue_length                      3870 non-null   int64
 31  Residue_perc                        3870 non-null   int64
 32  Stubble_use                         3870 non-null   int64
 33  Acre                                3870 non-null   float64
 34  Yield                               3870 non-null   int64
dtypes: datetime64[ns](3), float64(8), int64(23), object(1)
memory usage: 1.0+ MB

In [ ]:
dataset = dataset.drop(columns = ['CropTillageDate', 'Harv_date', 'Threshing_date'])

In [144]:
label = dataset['Yield']
features = dataset.drop(columns = ['ID', 'Yield', 'Block', 'Stubble_use', '1tdUrea'])

In [145]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor

In [146]:
(features_train, features_test, label_train, label_test) = train_test_split(features, label, test_size = 0.2)

In [147]:
import numpy as np
lin_reg = LinearRegression()
lin_reg.fit(features_train, label_train)
lin_reg_score = lin_reg.score(features_test, label_test)
lin_reg_predicted = lin_reg.predict(features_test)
lin_reg_rmse = np.sqrt(mean_squared_error(label_test, lin_reg_predicted))
print('Linear regression accuracy:', lin_reg_score, 'rmse:', lin_reg_rmse)

Linear regression accuracy: 0.8129948197535446 rmse: 211.77098122773825

In [148]:
svr = SVR()
svr.fit(features_train, label_train)
svr_score = svr.score(features_test, label_test)
svr_predicted = svr.predict(features_test)
svr_rmse = np.sqrt(mean_squared_error(label_test, svr_predicted))
print('SVR accuracy:', svr_score, 'rmse:', svr_rmse)

SVR accuracy: 0.07183990429058129 rmse: 471.79254788657727

In [149]:
tree = DecisionTreeRegressor()
tree.fit(features_train, label_train)
tree_score = tree.score(features_test, label_test)
tree_predicted = tree.predict(features_test)
tree_rmse = np.sqrt(mean_squared_error(label_test, tree_predicted))
print('tree accuracy:', svr_score, 'rmse:', svr_rmse)

tree accuracy: 0.07183990429058129 rmse: 471.79254788657727

In [150]:
test_data = pd.read_csv('test.csv')

In [151]:
test_data

,ID,District,Block,CultLand,CropCultLand,LandPreparationMethod,CropTillageDate,CropTillageDepth,CropEstMethod,RcNursEstDate,...,MineralFertAppMethod.1,Harv_method,Harv_date,Harv_hand_rent,Threshing_date,Threshing_method,Residue_length,Residue_perc,Stubble_use,Acre
0,ID_F9XXEXN2ADR2,Jamui,Khaira,20,13,TractorPlough,2022-07-24,4,Manual_PuddledLine,2022-07-03,...,Broadcasting,hand,2022-12-02,500.0,2022-12-28,hand,22,10,plowed_in_soil,0.272727
1,ID_SO3VW2X4QO93,Jamui,Khaira,25,25,TractorPlough,2022-07-24,5,Manual_PuddledRandom,2022-07-08,...,Broadcasting,hand,2022-11-12,150.0,2022-12-20,machine,28,10,plowed_in_soil,0.227273
2,ID_UKUQ7JM8E894,Nalanda,Rajgir,30,30,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-07,5,Manual_PuddledRandom,2022-06-24,...,Broadcasting,hand,2022-11-24,1200.0,2022-12-05,machine,28,10,plowed_in_soil,0.281250
3,ID_QUISMWEZR2H4,Vaishali,Mahua,15,10,WetTillagePuddling TractorPlough BullockPlough...,2022-07-04,5,Manual_PuddledRandom,2022-06-20,...,SoilApplied,hand,2022-10-15,300.0,2022-10-25,hand,30,10,plowed_in_soil,0.136364
4,ID_25JGI455VKCZ,Nalanda,Rajgir,30,10,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-21,3,Manual_PuddledRandom,2022-06-24,...,Broadcasting,machine,2022-11-20,NaN,2022-11-20,machine,26,40,plowed_in_soil,0.312500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1285,ID_6MMECMX3B728,Jamui,Khaira,20,16,TractorPlough,2022-07-23,4,Manual_PuddledLine,2022-07-05,...,Broadcasting,hand,2022-12-01,1200.0,2022-12-23,hand,23,10,plowed_in_soil,0.500000
1286,ID_GZ9YGWCLLMKN,Vaishali,Mahua,25,14,WetTillagePuddling TractorPlough FourWheelTrac...,2022-07-07,5,Manual_PuddledRandom,2022-07-09,...,NaN,hand,2022-10-15,450.0,2022-10-20,hand,28,10,plowed_in_soil,0.181818
1287,ID_01YVA2LJVYBR,Vaishali,Garoul,10,3,TractorPlough,2022-07-06,6,Manual_PuddledLine,2022-06-18,...,Broadcasting,hand,2022-10-28,600.0,2022-11-12,hand,29,10,plowed_in_soil,0.136364
1288,ID_YQRL2IOUU4SZ,Jamui,Jamui,10,10,TractorPlough BullockPlough,2022-07-22,4,Manual_PuddledRandom,2022-06-18,...,Broadcasting,hand,2022-11-25,90.0,2023-01-28,hand,29,10,plowed_in_soil,0.227273
1289,ID_VAX2N8ELPEZE,Nalanda,Noorsarai,15,15,TractorPlough FourWheelTracRotavator,2022-07-08,4,Manual_PuddledRandom,2022-06-22,...,NaN,hand,2022-11-04,250.0,2023-01-09,machine,26,10,plowed_in_soil,0.156250

In [154]:
columns_for_dropping = ['TransIrriCost',
 'OrgFertilizers',
 'Ganaura',
 'CropOrgFYM',
 'PCropSolidOrgFertAppMethod',
 'BasalUrea',
 '2tdUrea',
 '2appDaysUrea',
'CropTillageDate', 'Harv_date', 'Threshing_date',
'Block', 'Stubble_use', '1tdUrea']
test_data_after_dropping = test_data.drop(columns = columns_for_dropping)

In [155]:
identifier = test_data['ID']

In [156]:
identifier

0       ID_F9XXEXN2ADR2
1       ID_SO3VW2X4QO93
2       ID_UKUQ7JM8E894
3       ID_QUISMWEZR2H4
4       ID_25JGI455VKCZ
             ...
1285    ID_6MMECMX3B728
1286    ID_GZ9YGWCLLMKN
1287    ID_01YVA2LJVYBR
1288    ID_YQRL2IOUU4SZ
1289    ID_VAX2N8ELPEZE
Name: ID, Length: 1290, dtype: object

In [157]:
test_data_after_dropping

,ID,District,CultLand,CropCultLand,LandPreparationMethod,CropTillageDepth,CropEstMethod,RcNursEstDate,SeedingSowingTransplanting,SeedlingsPerPit,...,MineralFertAppMethod,FirstTopDressFert,1appDaysUrea,MineralFertAppMethod.1,Harv_method,Harv_hand_rent,Threshing_method,Residue_length,Residue_perc,Acre
0,ID_F9XXEXN2ADR2,Jamui,20,13,TractorPlough,4,Manual_PuddledLine,2022-07-03,2022-07-29,1.0,...,Broadcasting,Urea,23.0,Broadcasting,hand,500.0,hand,22,10,0.272727
1,ID_SO3VW2X4QO93,Jamui,25,25,TractorPlough,5,Manual_PuddledRandom,2022-07-08,2022-08-02,4.0,...,Broadcasting,Urea,23.0,Broadcasting,hand,150.0,machine,28,10,0.227273
2,ID_UKUQ7JM8E894,Nalanda,30,30,WetTillagePuddling TractorPlough FourWheelTrac...,5,Manual_PuddledRandom,2022-06-24,2022-07-08,2.0,...,Broadcasting,Urea,38.0,Broadcasting,hand,1200.0,machine,28,10,0.281250
3,ID_QUISMWEZR2H4,Vaishali,15,10,WetTillagePuddling TractorPlough BullockPlough...,5,Manual_PuddledRandom,2022-06-20,2022-07-10,2.0,...,SoilApplied,Urea,30.0,SoilApplied,hand,300.0,hand,30,10,0.136364
4,ID_25JGI455VKCZ,Nalanda,30,10,WetTillagePuddling TractorPlough FourWheelTrac...,3,Manual_PuddledRandom,2022-06-24,2022-07-22,1.0,...,Broadcasting,Urea,40.0,Broadcasting,machine,NaN,machine,26,40,0.312500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1285,ID_6MMECMX3B728,Jamui,20,16,TractorPlough,4,Manual_PuddledLine,2022-07-05,2022-07-30,1.0,...,Broadcasting,Urea,23.0,Broadcasting,hand,1200.0,hand,23,10,0.500000
1286,ID_GZ9YGWCLLMKN,Vaishali,25,14,WetTillagePuddling TractorPlough FourWheelTrac...,5,Manual_PuddledRandom,2022-07-09,2022-07-25,2.0,...,SoilApplied,NaN,NaN,NaN,hand,450.0,hand,28,10,0.181818
1287,ID_01YVA2LJVYBR,Vaishali,10,3,TractorPlough,6,Manual_PuddledLine,2022-06-18,2022-07-09,1.0,...,SoilApplied,Urea,30.0,Broadcasting,hand,600.0,hand,29,10,0.136364
1288,ID_YQRL2IOUU4SZ,Jamui,10,10,TractorPlough BullockPlough,4,Manual_PuddledRandom,2022-06-18,2022-07-26,4.0,...,Broadcasting,Urea Other,30.0,Broadcasting,hand,90.0,hand,29,10,0.227273
1289,ID_VAX2N8ELPEZE,Nalanda,15,15,TractorPlough FourWheelTracRotavator,4,Manual_PuddledRandom,2022-06-22,2022-07-13,1.0,...,Broadcasting,NaN,NaN,NaN,hand,250.0,machine,26,10,0.156250

In [158]:
test_data_after_dropping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1290 entries, 0 to 1289
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  1290 non-null   object
 1   District                            1290 non-null   object
 2   CultLand                            1290 non-null   int64
 3   CropCultLand                        1290 non-null   int64
 4   LandPreparationMethod               1290 non-null   object
 5   CropTillageDepth                    1290 non-null   int64
 6   CropEstMethod                       1290 non-null   object
 7   RcNursEstDate                       1247 non-null   object
 8   SeedingSowingTransplanting          1290 non-null   object
 9   SeedlingsPerPit                     1187 non-null   float64
 10  NursDetFactor                       1187 non-null   object
 11  TransDetFactor                      1187 non-null   object
 12  TransplantingIrrigationHours        1213 non-null   float64
 13  TransplantingIrrigationSource       1244 non-null   object
 14  TransplantingIrrigationPowerSource  1119 non-null   object
 15  StandingWater                       1211 non-null   float64
 16  NoFertilizerAppln                   1290 non-null   int64
 17  CropbasalFerts                      1214 non-null   object
 18  BasalDAP                            1099 non-null   float64
 19  MineralFertAppMethod                1290 non-null   object
 20  FirstTopDressFert                   1141 non-null   object
 21  1appDaysUrea                        1112 non-null   float64
 22  MineralFertAppMethod.1              1144 non-null   object
 23  Harv_method                         1290 non-null   object
 24  Harv_hand_rent                      1217 non-null   float64
 25  Threshing_method                    1290 non-null   object
 26  Residue_length                      1290 non-null   int64
 27  Residue_perc                        1290 non-null   int64
 28  Acre                                1290 non-null   float64
dtypes: float64(7), int64(6), object(16)
memory usage: 292.4+ KB

In [161]:
object_cols_for_imputing = []
for i in test_data_after_dropping.columns:
    if test_data_after_dropping[i].dtype == 'object' and test_data_after_dropping[i].isnull().sum() > 0:
        object_cols_for_imputing.append(i)
object_cols_for_imputing

['RcNursEstDate',
 'NursDetFactor',
 'TransDetFactor',
 'TransplantingIrrigationSource',
 'TransplantingIrrigationPowerSource',
 'CropbasalFerts',
 'FirstTopDressFert',
 'MineralFertAppMethod.1']

In [163]:
test_data_imputed = test_data_after_dropping.copy()
test_data_imputed[object_cols_for_imputing] = cathegorical_imputer.fit_transform(test_data_after_dropping[object_cols_for_imputing])
test_data_imputed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1290 entries, 0 to 1289
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  1290 non-null   object
 1   District                            1290 non-null   object
 2   CultLand                            1290 non-null   int64
 3   CropCultLand                        1290 non-null   int64
 4   LandPreparationMethod               1290 non-null   object
 5   CropTillageDepth                    1290 non-null   int64
 6   CropEstMethod                       1290 non-null   object
 7   RcNursEstDate                       1290 non-null   object
 8   SeedingSowingTransplanting          1290 non-null   object
 9   SeedlingsPerPit                     1187 non-null   float64
 10  NursDetFactor                       1290 non-null   object
 11  TransDetFactor                      1290 non-null   object
 12  TransplantingIrrigationHours        1213 non-null   float64
 13  TransplantingIrrigationSource       1290 non-null   object
 14  TransplantingIrrigationPowerSource  1290 non-null   object
 15  StandingWater                       1211 non-null   float64
 16  NoFertilizerAppln                   1290 non-null   int64
 17  CropbasalFerts                      1290 non-null   object
 18  BasalDAP                            1099 non-null   float64
 19  MineralFertAppMethod                1290 non-null   object
 20  FirstTopDressFert                   1290 non-null   object
 21  1appDaysUrea                        1112 non-null   float64
 22  MineralFertAppMethod.1              1290 non-null   object
 23  Harv_method                         1290 non-null   object
 24  Harv_hand_rent                      1217 non-null   float64
 25  Threshing_method                    1290 non-null   object
 26  Residue_length                      1290 non-null   int64
 27  Residue_perc                        1290 non-null   int64
 28  Acre                                1290 non-null   float64
dtypes: float64(7), int64(6), object(16)
memory usage: 292.4+ KB

In [166]:
object_cols = []
for i in test_data_imputed.columns:
    if test_data_imputed[i].dtype == 'object' and i != 'ID':
        object_cols.append(i)

In [167]:
object_cols

['District',
 'LandPreparationMethod',
 'CropEstMethod',
 'RcNursEstDate',
 'SeedingSowingTransplanting',
 'NursDetFactor',
 'TransDetFactor',
 'TransplantingIrrigationSource',
 'TransplantingIrrigationPowerSource',
 'CropbasalFerts',
 'MineralFertAppMethod',
 'FirstTopDressFert',
 'MineralFertAppMethod.1',
 'Harv_method',
 'Threshing_method']

In [168]:
dataset_encoded = test_data_imputed.copy()
for i in object_cols:
    dataset_encoded[i] = encoder.fit_transform(test_data_imputed[i])
dataset_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1290 entries, 0 to 1289
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  1290 non-null   object
 1   District                            1290 non-null   int64
 2   CultLand                            1290 non-null   int64
 3   CropCultLand                        1290 non-null   int64
 4   LandPreparationMethod               1290 non-null   int64
 5   CropTillageDepth                    1290 non-null   int64
 6   CropEstMethod                       1290 non-null   int64
 7   RcNursEstDate                       1290 non-null   int64
 8   SeedingSowingTransplanting          1290 non-null   int64
 9   SeedlingsPerPit                     1187 non-null   float64
 10  NursDetFactor                       1290 non-null   int64
 11  TransDetFactor                      1290 non-null   int64
 12  TransplantingIrrigationHours        1213 non-null   float64
 13  TransplantingIrrigationSource       1290 non-null   int64
 14  TransplantingIrrigationPowerSource  1290 non-null   int64
 15  StandingWater                       1211 non-null   float64
 16  NoFertilizerAppln                   1290 non-null   int64
 17  CropbasalFerts                      1290 non-null   int64
 18  BasalDAP                            1099 non-null   float64
 19  MineralFertAppMethod                1290 non-null   int64
 20  FirstTopDressFert                   1290 non-null   int64
 21  1appDaysUrea                        1112 non-null   float64
 22  MineralFertAppMethod.1              1290 non-null   int64
 23  Harv_method                         1290 non-null   int64
 24  Harv_hand_rent                      1217 non-null   float64
 25  Threshing_method                    1290 non-null   int64
 26  Residue_length                      1290 non-null   int64
 27  Residue_perc                        1290 non-null   int64
 28  Acre                                1290 non-null   float64
dtypes: float64(7), int64(21), object(1)
memory usage: 292.4+ KB

In [169]:
cols_for_imputation = []
for i in dataset_encoded.columns:
    if dataset_encoded[i].isnull().sum() > 0:
        cols_for_imputation.append(i)
cols_for_imputation

['SeedlingsPerPit',
 'TransplantingIrrigationHours',
 'StandingWater',
 'BasalDAP',
 '1appDaysUrea',
 'Harv_hand_rent']

In [172]:
dataset = dataset_encoded.copy()
dataset[cols_for_imputation] = imputer.fit_transform(dataset_encoded[cols_for_imputation])

In [174]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1290 entries, 0 to 1289
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  1290 non-null   object
 1   District                            1290 non-null   int64
 2   CultLand                            1290 non-null   int64
 3   CropCultLand                        1290 non-null   int64
 4   LandPreparationMethod               1290 non-null   int64
 5   CropTillageDepth                    1290 non-null   int64
 6   CropEstMethod                       1290 non-null   int64
 7   RcNursEstDate                       1290 non-null   int64
 8   SeedingSowingTransplanting          1290 non-null   int64
 9   SeedlingsPerPit                     1290 non-null   float64
 10  NursDetFactor                       1290 non-null   int64
 11  TransDetFactor                      1290 non-null   int64
 12  TransplantingIrrigationHours        1290 non-null   float64
 13  TransplantingIrrigationSource       1290 non-null   int64
 14  TransplantingIrrigationPowerSource  1290 non-null   int64
 15  StandingWater                       1290 non-null   float64
 16  NoFertilizerAppln                   1290 non-null   int64
 17  CropbasalFerts                      1290 non-null   int64
 18  BasalDAP                            1290 non-null   float64
 19  MineralFertAppMethod                1290 non-null   int64
 20  FirstTopDressFert                   1290 non-null   int64
 21  1appDaysUrea                        1290 non-null   float64
 22  MineralFertAppMethod.1              1290 non-null   int64
 23  Harv_method                         1290 non-null   int64
 24  Harv_hand_rent                      1290 non-null   float64
 25  Threshing_method                    1290 non-null   int64
 26  Residue_length                      1290 non-null   int64
 27  Residue_perc                        1290 non-null   int64
 28  Acre                                1290 non-null   float64
dtypes: float64(7), int64(21), object(1)
memory usage: 292.4+ KB

In [177]:
dataset_features = dataset.drop(columns = ['ID', 'RcNursEstDate'])

In [178]:
dataset_predictions = lin_reg.predict(dataset_features)

In [179]:
dataset_predictions

array([628.35896333, 422.25752337, 444.13119439, ..., 248.22553616,
       395.61913633, 327.85533333], shape=(1290,))

In [182]:
submission_file = pd.DataFrame({
    'ID': identifier,
    'Yield': dataset_predictions
})

In [183]:
submission_file.to_csv('my_submission.csv', index=False)

In [185]:
from IPython.display import FileLink

In [186]:
FileLink('my_submission.csv')

C:\Users\filip\my_submission.csv